set(INDEX 0)

while(INDEX LESS 5)
    message("index = " ${INDEX})
    math(EXPR INDEX "${INDEX} + 1")
endwhile(INDEX LESS 5)

message("foreach for range")
foreach(VAR RANGE 3)
    message("VAR(range) = " ${VAR})
endforeach()
foreach(VAR RANGE 2 10 2)
    message("VAR(range+start/end/step) = " ${VAR})
endforeach()

message("foreach for lists and variadic items")
set(MY_VARS 1 2 3 4 5)
foreach(VAR IN LISTS MY_VARS ITEMS 6 7 8 9)
    message("VAR = " ${VAR})
endforeach()

message("Shorter foreach:")
foreach(VAR 6 7 8 9)
    message("\t\tVAR = " ${VAR})
endforeach()

message("foreach for zip lists:")
set(MY_VARS_2 one two three four five)
foreach(VAR IN ZIP_LISTS MY_VARS MY_VARS_2)
    message("${VAR_0} -> ${VAR_1}")
endforeach()
foreach(num txt IN ZIP_LISTS MY_VARS MY_VARS_2)
    message("\t${num} -> ${txt}")
endforeach()
