global using System.Collections.Immutable;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using UnoMediaCollection.DataContracts;
global using UnoMediaCollection.DataContracts.Serialization;
global using UnoMediaCollection.Models;
global using UnoMediaCollection.Services.Caching;
global using UnoMediaCollection.Services.Endpoints;
global using ApplicationExecutionState = Windows.ApplicationModel.Activation.ApplicationExecutionState;
